### ISSUE TITLE
Installing the Library

### ISSUE THREAD

**Issue by jonboone1** [baronet2/FirstCyclingAPI#22]
Hey there, just wondering if this library is available on PyPi? I don't see anything in the docs about how to install this library.

**Comment by baronet2** [comment]
Hello, thanks for reaching out. The library isn't currently available on PyPi, and I haven't had much time to work on it recently. The easiest way for you to use the package is probably to `git clone` it locally. Let me know if that works for you.

**Comment by jonboone1** [comment]
Got it, okay no problem. Appreciate the quick response.
